# This is a generated file. Not intended for manual editing.
services:
  cursor-pagination:
    build:
      context: "C:\\Users\\giuse\\RiderProjects\\CursorPagination"
      dockerfile: "CursorPagination/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/CursorPagination.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "cursor-pagination:dev"
    ports: []
    volumes:
    - "C:\\Users\\giuse\\RiderProjects\\CursorPagination\\CursorPagination:/app:rw"
    - "C:\\Users\\giuse\\RiderProjects\\CursorPagination:/src:rw"
    - "C:\\Users\\giuse\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
