# This is a generated file. Not intended for manual editing.
services:
  cursor-pagination:
    build:
      context: "C:\\Users\\giu_a\\RiderProjects\\cursor-pagination"
      dockerfile: "CursorPagination/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "cursor-pagination:dev"
    ports:
    - "127.0.0.1:57020:57000"
    - "127.0.0.1:57220:57200"
    - "127.0.0.1:57420:57400"
    volumes:
    - "C:\\Users\\giu_a\\RiderProjects\\cursor-pagination\\CursorPagination:/app:rw"
    - "C:\\Users\\giu_a\\RiderProjects\\cursor-pagination:/src:rw"
    - "C:\\Users\\giu_a\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\giu_a\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.6\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\giu_a\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\giu_a\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_3_21_19_40_43:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
