services:
  cursor-pagination:
    container_name: 'cursor-pagination'
    image: cursor-pagination
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=http://+:8080;https://+:443
      - ASPNETCORE_URLS=http://+:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    build:
      context: .
      dockerfile: src/CursorPagination/Dockerfile
    ports:
       - "5000:8080"
       - "5001:443"
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - cursor-db
            
  cursor-db: 
    image: postgres:latest
    container_name: Database
    hostname: cursor-db
    environment:
      - POSTGRES_DB=cursordbnew
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data_new
    ports:
      - 5100:5432
      
  cursor-db-management:
    image: dpage/pgadmin4:latest
    container_name: Database_management
    depends_on:
      - cursor-db
    volumes:
      - ./.files/dev_servers.json:/pgadmin4/servers.json
      - ./.containers/database_management:/var/lib/pgadmin
    ports:
      - "5101:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888